[package]
name = "shadow-rs"
version = "0.6.7"
authors = ["baoyachi <liaoymxsdl@gmail.com>"]
edition = "2018"
description = "A build-time information stored in your rust project"
keywords = ["shadow", "build-script", "build", "script", "compile"]
readme = "README.md"
categories = ["development-tools", "development-tools::build-utils"]
repository = "https://github.com/baoyachi/shadow-rs"
license = "MIT AND Apache-2.0"
exclude = ["shadow-rs.png"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.13"
git2 = { version = "0.13.20", default-features = false, optional = true }

[features]
default = ["git2"]

[workspace]
members = ["example_shadow", "example_shadow_hook"]
