[package]
name = "shadow-rs"
version = "0.3.19"
authors = ["baoyachi <liaoymxsdl@gmail.com>"]
edition = "2018"
description = "Build script by Rust"
keywords = ["shadow", "build-script","build","metadata","compile"]
readme = "README.md"
repository = "https://github.com/baoyachi/shadow-rs"
license = "MIT AND Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.13"
git2 = "0.13.8"
