name: ci
on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Check fix
        run: cargo fix
      - name: Check with Windows clippy
        if: runner.os == 'Windows'
        run: cargo clippy --all
      - name: Check with clippy
        if: runner.os != 'Windows'
        run: RUSTFLAGS="-D warnings" cargo clippy --all
      - name: Build Release
        run: cargo build --release
      - name: Run tests
        run: cargo test --all --verbose

#      # examples
#      - name: Check examples format
#        run: cargo fmt --all -- --check
#        working-directory: ./example_shadow
#      - name: Check examples with clippy
#        run: RUSTFLAGS="-D warnings" cargo clippy --all
#        working-directory: ./example_shadow
#      - name: Build examples
#        run: cargo build --all --verbose
#        working-directory: ./example_shadow
#
#      # build on nightly
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: nightly
#          override: true
#          components: clippy, rustfmt
#      - name: Build on nightly without features
#        run: cargo build --release
#      - name: Build on nightly
#        run: cargo build --all --verbose