
name: build

on:
  push:
    branches: [master,issue_8]
  pull_request:
    branches: [master,issue_8]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Lint
        run: |
              cargo run
#              cargo fix
#              cargo fix
#              cargo build